created template for thesis
updated readme

removed ds_store files

readme updated

readme updated

readme updated

minor editrs

readme updates

readme updates

readme updates

readme updates

readme updates

readme updates

fixed comment syntax typo

Remove -V from docx, html options; add standalone

The variable declarations in the Makefile under docx and html are
superfluous, in case of docx because they can't be used and in case of
html because there is no template provided or because "documentclass"
applies only to LaTeX.

The "standalone" option is also needed for the table of contents to show
up in the HTML output.

Added fabfile

Replicated Makefile in Fabric

Add an html template and html styling

html styling fixed

Grunt task file to watch markdown files and auto-compile them

Fix tightlist in pandoc 1.14

pandoc 1.14 introduced \tightlist
Related links:
https://github.com/jgm/pandoc/pull/1571#issuecomment-106298268
https://github.com/osener/markup.rocks/issues/4
https://github.com/rstudio/rmarkdown/issues/439

use Palatino instead of non existing Palatino Linotype

remove two spaces at end of paragraphs

update pdf output

small fix. Removed one space too much

update output again

add paragraph start indention as comment (when required)

test build with travis ci

preamble fixes for travis ci

travis html build

redirect msgs for travis

Disable custom fonts

Update Travis configuration to use newer version of Pandoc and TeX Live

Add Travis CI build status in the readme

update getting started details. cite-proc. latex distribution

typo

Update README.md

Add grunt-express and grunt-open dependencies

Add new task in Gruntfile to serve the HTML with LiveReload

Add npm script alias for LiveReload

Add instructions in the readme

Grunt notifications options

The options previously set for grunt-notify weren't enabled. I added `notify_hooks` to the task to be run.
I've also removed the title in the options, the title now used is the one from package.json.

make should also work in directories with spaces

add missing =

add sample html

Document issue #15

update subscript size. fix #21

undo unintentional commits

Smaller font size in the references

Updated README.md with installation steps

On my machine `make pdf` resulted in a lot `make: *** [pdf] Error 43` errors. The causes were missing LaTeX packages.
After installing and updating the packages everything worked smoothly.

add example code block. ref #23.

specify syntax highlighting style. Ref #23

Update Makefile

add link to Zenodo

fix #30 by making all links noncolored

add abbreviations page

change file naming

Add roman numerals to TOC, fix #39

add pdf

rename files #43

rename introduction & literature to chapter x

The naming for introducting.md and literature.md was confusing. When compiling to pdf, both files are defacto titled Chapter 1 and Chapter 2 respectively. This commit reflects this naming convention.

example scaling for images. ref #15

delete "verbose" option in pdf module, it is not available in some pandoc versions

Using pandoc-shortcaption

Adding "pandoc-shortcaption" to .travis.yml

Change pandoc to 1.17.2 since that worked in Docker. 1.15 did not.

@martisak fixed short captions

Update README.md

Image size can be specified. Thanks @rudolfbyker.

Update README.md

clean up list of figures

require install of pandoc-shortcaption

tidy

correct line spacing to 1.5

revert pandoc-shortcaption #47 for now. fixes #48.

Minor formatting changes in README.md

--latex-engine -> --pdf-engine. ref #69

fix build

add and close #36 by @tobiasbueschel. ref #70

update pdf

Fixed '! LaTeX Error: Environment cslreferences undefined.'

Use secnumdepth variable if set

Currently the section numbering depth is hard-coded to 5. Thus passing the variable `secnumdepth` to pandoc will have no effect.

I suggest to adapt the `secnumdepth` logic from pandoc's integrated [template.tex](https://github.com/jgm/pandoc-templates/blob/master/default.latex)

Added xnos annotation, edited makefile

Added pandoc xnos compatibility

Fixed issue with lof showing up at top of document due to stray yaml header

Edited install instructions and added references to relevant blog post.

Corrected blog post link

Added new installs to travis.yml

Added example of non-shortcaption usage

Delete modules.xml

Delete misc.xml

Delete phd_thesis_markdown.iml

Delete vcs.xml

Update .travis.yml

Removed extraneous comma

Added xnos filters to Tex command, re-added template filters.

Migrated `install.sh` to xnos branch

Added install recipe

Fixed typo & added reference to new recipe

Added university logo back in

Added additional explanation as per @davidverweij

Moved variables into a .ylm to use title and name in HTML

Fix "help" make recipe

- Remove tabs causing misalignment
- Remove meaningless whitespace which make editing more difficult

Run help recipe on CI

Remove pandoc-citeproc install

Pandoc is not installed including citeproc.

Add separate mac and linux install

Attempt to fix travis

Have another go at travis...

Fix miniconda version

Fix brew install for mactex

Add quickstart

Add update of tlmgr

Try sudo

Try just py3.6

Attempt to test linux too

Remove env statements improve comments

Put them back!

Add verbatim blocks for if statements

https://stackoverflow.com/questions/38789253/running-script-conditionally-does-not-work-in-travis-yml-why

Actually use OS_NAME for conda install

Add sudo to apt-get install

Try to fix make pdf issue

Check brew is up-to-date

Fix calls to tlmgr for linux

Remove linux build for now

Add python versions

Initialise travis with updated homebrew and apt, and installed texlive

Hopefully this solves some issues and maybe even cuts the build time

Try doing tlmgr update before conda install of pandoc

Add linux notes

Try removing from path

This issue suggests we could be using an old install of texlive.
Conda should be putting pandoc on the path anyway. I wonder how it
choses what tex version to use.
https://tex.stackexchange.com/questions/567050/how-can-i-install-l3backend-pdfmode-def

Add debug code

fix typo

Try to fix mac build error by removing fixltx2e

This packages is depreciated for modern lex releases (post 2015).
https://tex.stackexchange.com/questions/287146/how-to-use-fixltx2e-only-when-necessary

Attempt to fix linux issue `cannot setup TLPDB in /home/travis/texmf`

https://tex.stackexchange.com/questions/137428/tlmgr-cannot-setup-tlpdb

Try to fix /usr/bin/tlmgr: Initialization failed (in setup_unix_one):

```
$ make install
bash /home/travis/build/tompollard/phd_thesis_markdown/install_linux.sh
(running on Debian, switching to user mode!)
/usr/bin/tlmgr: Initialization failed (in setup_unix_one):
/usr/bin/tlmgr: could not find a usable xzdec.
/usr/bin/tlmgr: Please install xzdec and try again.
tlmgr: Couldn't set up the necessary programs.
Installation of packages is not supported.
Please report to texlive@tug.org.
Use of uninitialized value $r in split at /usr/bin/tlmgr line 3882.
tlmgr: Cannot find main repository, you have to tag one as main!
Makefile:37: recipe for target 'install' failed
make: *** [install] Error 1
The command "make install" failed and exited with 2 during .
```

https://tex.stackexchange.com/questions/180230/kubuntu-texlive-manually-installed-tlmgr-not-working

Addressing homebrew warning to update path

You must restart your terminal window for the installation of MacTex CLI tools to take effect.
Alternatively, Bash and Zsh users can run the command:
  eval "$(/usr/libexec/path_helper)"

Echo $PATH for debugging

Fix if statement

Give up on linux...again. And try remove brew update (for speed)

Linux now stuck on error I recognise from advice:

0.12s$ if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    eval "$(/usr/libexec/path_helper)"
    sudo tlmgr update --self
  elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
    tlmgr init-usertree
    echo on linux we cannot update apt installed texlive c.f.
    echo https://tex.stackexchange.com/questions/551383/cant-run-tex-lives-tlmgr-in-a-github-action
    echo https://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu
  fi

(running on Debian, switching to user mode!)
tlmgr: action init-usertree returned a warning.

...

$ make install
bash /home/travis/build/tompollard/phd_thesis_markdown/install_linux.sh
(running on Debian, switching to user mode!)
Unknown directive ...containerchecksum 57a177b65450718631f36bfd8db0f2d1bff788f3bf147137b6412714cc945c7e08832f14f9e7e659adf7e072a91f13a2ea27fe3161cd9b60313bc956f1f543c6... , please fix it! at /usr/share/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 7085.
Makefile:37: recipe for target 'install' failed
make: *** [install] Error 25
The command "make install" failed and exited with 2 during .

https://tex.stackexchange.com/questions/313768/why-getting-this-error-tlmgr-unknown-directive

I think the way forward would be to customise the install of texlive for linux.

Don't update brew

Add a basic explanation about how pandoc handles input

Add more logging printout for debugging

Make it clear where the mardown files go

Don't update brew...

Trying this to compare with previous build

Print the tlmgr log

Try updating l3backend too

travis needs the homebrew update option set true

Else we get the following stack:
```
brew
Installing Homebrew Packages
6.51s$ rvm $brew_ruby do brew bundle --verbose --global
/usr/local/bin/brew tap homebrew/bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 101 (delta 4), reused 28 (delta 1), pack-reused 0
Receiving objects: 100% (101/101), 51.37 KiB | 2.23 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Tapped (109 files, 268.1KB).
Error: Unknown command: bundle
before_install.1
0.01s$ echo $PATH
0.05s$ if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    eval "$(/usr/libexec/path_helper)"
    sudo tlmgr update --self
  elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
    tlmgr init-usertree
    echo MSG FROM JO:
    echo on linux we cannot update apt installed texlive
    echo next steps to fix see commit msg: https://github.com/tompollard/phd_thesis_markdown/pull/100/commits/85fd9e7ac413a34066b79f1e49b3e1d3efdeac00
    echo c.f. https://tex.stackexchange.com/questions/551383/cant-run-tex-lives-tlmgr-in-a-github-action
    echo and https://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu

  fi

sudo: tlmgr: command not found
```

Extended README.md to include Troubleshooting etc.

Added:
* Troubleshooting
* More info to "how does it work"?

Ignore .vscode

Dispense with && and make script fail upon error

Also added comments re updating all

Updated markdown chapters to include further examples.

* Section references - chapter 1
  * Uses plain LaTeX \ref{...} to indicate how to refer to each section.
* Use of URL links - chapter 1

Still todo:
* footnotes
* label arbitrary sections like it was an equation (e.g. the code snippet)

Commit the .tex generated by make tex

Commit img files generated by make html

I think this makes sense, given that we are tracking both thesis.pdf (a large
binary file), and thesis.html (a file which refers to these images).

Add the docx binary file

Debatable whether this is really required. I do it for completeness. I don't
know if we will be able to track changes the the file i.e. will it stay the same
if we generate from the same markdown?

Fix section and equation references

Add extra packages for latex math

Regenerated output

Add note about latex

Add examples of using pandoc-secnos